/**
 * Interface to read and save file like objects from a backend system.
 */
import {Observable} from 'rxjs';
import {IFile} from './i-file';
import {IFileAccessConfiguration} from './i-file-access-configuration';
import {IFileDescriptionDirectory} from './i-file-description-directory';
import {IFileDescription} from './i-file-description';

export interface IFileAccessService {

    /**
     * Load a file from the backend system.
     * @param description backend dependent description of the file to load.
     * @return Observable of the loaded file.
     */
    load(description: IFileDescription): Observable<IFile|IFileDescriptionDirectory>;

    /**
     * Save a file in the backend.
     * @param file file loaded from the same backend.
     * @return TODO information about successful or failed save.
     */
    save(file: IFile): Observable<any>;

    /**
     * Serialize a configuration to store it.
     * @param configuration configuration to be serialized.
     * @return serialized form that can be deserialized.
     */
    serialize(configuration: IFileAccessConfiguration): string;

    /**
     * Create a configuration from a stored string (generated by serialize()).
     * @param serialzedConfiguration stored configuration string
     * @return deserialized version.
     */
    deserialize(serialzedConfiguration: string): IFileAccessConfiguration;
}
